"""URL configuration for the default site (generated by djangocms-agent bin/new-site.py).

Order matters: /health/ and admindocs must come before the cms.urls include (admindocs also before admin/,
or the admin catch-all swallows it); the cms.urls include must be last because it matches everything.

admindocs prefix: Django's own documented default is ``admin/doc/``; this site uses ``admin/docs/``
(the prefix the skill documents). Pick one and use it consistently.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve as serve_media

from .health import health

urlpatterns = [
    path('health/', health, name='health'),  # container healthcheck; before the CMS catch-all
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]
if getattr(settings, 'USE_DEBUG_TOOLBAR', False):  # same switch as settings.py (DEBUG and DJANGO_DEBUG_TOOLBAR)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # dev-only media
elif getattr(settings, 'SERVE_MEDIA', False):
    # DEBUG off and DJANGO_SERVE_MEDIA=1 (the container default): Django serves uploads itself. Put
    # nginx/caddy in front and unset the flag for heavy traffic.
    urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve_media, {'document_root': settings.MEDIA_ROOT})]
urlpatterns += [path('', include('cms.urls'))]
