# Generated by Django 5.2.17 on 2026-10-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0045_pageurl_site_unique_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlBlock',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('html', models.TextField(help_text='Trusted HTML, rendered as-is.')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
